import type { Metadata } from "next";
import { type ReactNode } from "react";

import "flag-icons/css/flag-icons.min.css";

import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

type RootLayoutProps = {
	children: ReactNode;
};

// Since we have a `not-found.tsx` page on the root, a layout
// file is required, even if it's just passing children through.
export default function RootLayout({ children }: RootLayoutProps) {
	return children;
}
